abstract class NewsStates {}
class NewsInitialState extends NewsStates{}
class NewsBottomNavState extends NewsStates{}
class NewsGetBusinessDataLoadingsState extends NewsStates{}
class NewsGetBusinessDataSuccessState extends NewsStates{}
class NewsGetBusinessDataErrorState extends NewsStates{}
class NewsGetScienceDataLoadingsState extends NewsStates{}
class NewsGetDataScienceSuccessState extends NewsStates{}
class NewsGetDataScienceErrorState extends NewsStates{}
class NewsGetSportsDataLoadingsState extends NewsStates{}
class NewsGetSportsDataSuccessState extends NewsStates{}
class NewsGetSportsDataErrorState extends NewsStates{}
class NewsGetSearchLoadingsState extends NewsStates{}
class NewsGetSearchSuccessState extends NewsStates{}
class NewsGetSearchErrorState extends NewsStates{}
class NewsChangeThemeState extends NewsStates{}